### ISSUE TITLE
No connection with Raspberry pi3 board

### ISSUE THREAD

**Issue by anamozov** [googlesamples/android-BluetoothLeGatt#37]
My Android phone is not connecting with GATT service installed on my Raspberry pi 3 board? No issues but connection state is always "disconnected" 
Waiting for  your help ASAP

**Comment by hammmmy** [comment]
are you sending connection request to the correct bluetooth address of the raspberry pi?

**Comment by anamozov** [comment]
Yes I was trying to connect bluetooth address of the raspberry pi 3. I have
solved this problem, thank you anyway for your response

**Comment by hammmmy** [comment]
Great .. just for reference, how did u end up solving the problem? I am writing a medium post on bluetooth on Android things these days and would be helpful to include that in the post

**Comment by btmcmahan** [comment]
anamozov I have the same problem.  How did you solve this?

**Comment by Surimari** [comment]
Hello,
I’m struggling with the same problem. Did you find a solution on this? Problem details see below.

I’ve just installed the android developer ble project (https://developer.android.com/guide/topics/connectivity/bluetooth-le.html) on my phone (nexus 5) and started the bluez gatt server example on my raspberry pi 3. With the Nordic semiconductors android nrf tool I can connect to the server running on raspberry and read, write values. But not with the android sample program. But if I create a server with another phone, using the nrf tool, I can connect to that with the android developer app. 

Because I'm not really familiar with android programming, I'm having a quite hard time debugging this issue. Can you maybe help me, or do you have a clue on that? I would really appreciate any help.

**Comment by anamozov** [comment]
Good evening.
This problem occurred months ago, and it was my temporary project.
Now I cannot even remember the problem itself.
I am sorry that I cannot help you now.
Wish you can solve this problem.
Best regards
Abdulaziz Namozov

**Comment by Surimari** [comment]
Hi,
Thank you for answering. Please let us know if you remember the solution. :)
Anybody has an idea? Btmcmahan, did you find a solution?

**Comment by Surimari** [comment]
Hey,
I've found the solution on stackoverflow.
Use this in BluetoothLeService.Java:
mBluetoothGatt = device.connectGatt(this, false, mGattCallback,TRANSPORT_LE);

instead of this:
mBluetoothGatt = device.connectGatt(this, false, mGattCallback);

See here: https://stackoverflow.com/questions/46273499/trouble-connecting-android-app-to-raspberry-pi-3-over-ble
