### ISSUE TITLE
How to import it into the eclipse?

### ISSUE THREAD

**Issue by zlc111** [googlesamples/android-BluetoothLeGatt#4]
Hi, I'm new to the BLE and android.Unfortunately, I have got into trouble with importing the project into the eclipse. When I import it as usual, something wrong, there is a red cross under the res folder and no files under the src folder. But I import some similar projects, nothing happened. So what's wrong? Maybe I need to do something special for this project?Thanks a lot.

**Comment by ryanseys** [comment]
Hi @zlc111, we recommend you use Android Studio to build this sample as it provides all the necessary tools built-in and configured correctly (such as Gradle for building) in order to get you up and running as fast as possible. You can download Android Studio from the [official website](https://developer.android.com/sdk/index.html). Let me know if you require any additional assistance getting set up with Android Studio.
